/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Administrator;
import domen.Grupa;
import domen.Putnik;
import forme.grupa.NovaGrupaForma;
import forme.grupa.DetaljiGrupeForma;
import forme.putnik.NoviPutnikForma;
import forme.putnik.PretragaPutnikaForma;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.KlijentKontroler;
import model.TableModelGrupe;
import sesija.Sesija;

/**
 *
 * @author Jovana
 */
public class GlavnaForma extends javax.swing.JFrame {
Administrator ulogovani;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Sesija.getInstance().getUlogovani();
        txtUlogovani.setText(ulogovani.toString());
        setTitle("Glavna klijentska forma");
        TableModelGrupe tm= new TableModelGrupe();
        Thread thread=new Thread(tm);
        tblGrupe.setModel(tm);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUlogovani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtParametar = new javax.swing.JTextField();
        tblDodajNovuGrupu = new javax.swing.JButton();
        tblIzmeniGrupu = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnPutnik = new javax.swing.JMenu();
        mniUnesiPutnika = new javax.swing.JMenuItem();
        mniPretraziPutnika = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniOdjaviSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Trenutno ulogovani korisnik");

        txtUlogovani.setEditable(false);
        txtUlogovani.setBackground(new java.awt.Color(204, 204, 204));
        txtUlogovani.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblGrupe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGrupe);

        jLabel2.setText("Pretrazite grupe po destinaciji");

        txtParametar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParametarActionPerformed(evt);
            }
        });
        txtParametar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParametarKeyReleased(evt);
            }
        });

        tblDodajNovuGrupu.setText("Dodaj novu grupu");
        tblDodajNovuGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDodajNovuGrupuActionPerformed(evt);
            }
        });

        tblIzmeniGrupu.setText("Detalji grupe");
        tblIzmeniGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblIzmeniGrupuActionPerformed(evt);
            }
        });

        mnPutnik.setText(" Putnik");

        mniUnesiPutnika.setText("Novi putnik");
        mniUnesiPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUnesiPutnikaActionPerformed(evt);
            }
        });
        mnPutnik.add(mniUnesiPutnika);

        mniPretraziPutnika.setText("Pretrazi putnika");
        mniPretraziPutnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPretraziPutnikaActionPerformed(evt);
            }
        });
        mnPutnik.add(mniPretraziPutnika);

        jMenuBar1.add(mnPutnik);

        jMenu1.setText(" Odjava");

        mniOdjaviSe.setText("Odjavi se  ");
        mniOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOdjaviSeActionPerformed(evt);
            }
        });
        jMenu1.add(mniOdjaviSe);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUlogovani, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(txtParametar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tblDodajNovuGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tblIzmeniGrupu, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblDodajNovuGrupu)
                    .addComponent(tblIzmeniGrupu))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniPretraziPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPretraziPutnikaActionPerformed
       new PretragaPutnikaForma(this, true).setVisible(true);
    }//GEN-LAST:event_mniPretraziPutnikaActionPerformed

    private void mniUnesiPutnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUnesiPutnikaActionPerformed
       new NoviPutnikForma(this, true).setVisible(true);
    }//GEN-LAST:event_mniUnesiPutnikaActionPerformed

    private void mniOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOdjaviSeActionPerformed
        int rezultat = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite sa sistema?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (rezultat == JOptionPane.NO_OPTION) {
            return;
        }

        if (rezultat== JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mniOdjaviSeActionPerformed

    private void tblDodajNovuGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDodajNovuGrupuActionPerformed
        new NovaGrupaForma(this, true,ulogovani).setVisible(true);
    }//GEN-LAST:event_tblDodajNovuGrupuActionPerformed

    private void tblIzmeniGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblIzmeniGrupuActionPerformed
    int row = tblGrupe.getSelectedRow();
        
        if(row<0){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje grupe po zadatoj vrednoti");
            return;
        }

        if (row >= 0) {
           Grupa g = ((TableModelGrupe) tblGrupe.getModel()).getSelectedGrupa(row);
            JOptionPane.showMessageDialog(this, "Sistem je uspesno ucitao grupu");
            new DetaljiGrupeForma(this, true, g).setVisible(true);
        }
       
    }//GEN-LAST:event_tblIzmeniGrupuActionPerformed

    private void txtParametarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParametarKeyReleased
        String param = txtParametar.getText();
        ((TableModelGrupe) tblGrupe.getModel()).setParametar(param);
        JOptionPane.showMessageDialog(this, "Sistem je uspesno pronasao grupu");
    }//GEN-LAST:event_txtParametarKeyReleased

    private void txtParametarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParametarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParametarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnPutnik;
    private javax.swing.JMenuItem mniOdjaviSe;
    private javax.swing.JMenuItem mniPretraziPutnika;
    private javax.swing.JMenuItem mniUnesiPutnika;
    private javax.swing.JButton tblDodajNovuGrupu;
    private javax.swing.JTable tblGrupe;
    private javax.swing.JToggleButton tblIzmeniGrupu;
    private javax.swing.JTextField txtParametar;
    private javax.swing.JTextField txtUlogovani;
    // End of variables declaration//GEN-END:variables

    


    public void refresujTabelu() {
        TableModelGrupe tm=(TableModelGrupe) tblGrupe.getModel();
        tm.refresujTabelu();
    }

   
}
