/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.grupa;

import domen.Clan;
import domen.Grupa;
import domen.Izlet;
import domen.Putnik;
import domen.Vodic;
import forme.GlavnaForma;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentKontroler;
import model.TableModelClanovi;

/**
 *
 * @author Jovana
 */
public class DetaljiGrupeForma extends javax.swing.JDialog {
Grupa g;
    /**
     * Creates new form PretragaGrupeForma
     */
    public DetaljiGrupeForma(java.awt.Frame parent, boolean modal,Grupa g) {
        super(parent, modal);
        initComponents();
        this.g=g;
        setLocationRelativeTo(null);
        setTitle("Detalji grupe");
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVodic = new javax.swing.JComboBox<>();
        cmbPrevoz = new javax.swing.JComboBox<>();
        cmbIzlet = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnOtkazi1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDatumPolaska = new javax.swing.JTextField();
        txtKAPACITET = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbPutnik = new javax.swing.JComboBox<>();
        cbFakulativno = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        btnDodajClana = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnObrisiGrupu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbVodic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPrevoz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus1", "Bus2", "Bus3", "Bus4" }));

        cmbIzlet.setBackground(new java.awt.Color(204, 204, 204));
        cmbIzlet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIzlet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Izlet");

        btnIzmeni.setText("Izmeni grupu");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel2.setText("Vodic");

        btnOtkazi1.setText("Otkazi");
        btnOtkazi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkazi1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Prevoz");

        jLabel4.setText("Datum polaska");

        jLabel5.setText("Kapacitet");

        txtDatumPolaska.setText("1.9.2029");

        txtKAPACITET.setText("60");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Dodatni izleti");

        jLabel8.setText("Napomena");

        cmbPutnik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane1.setViewportView(txtNapomena);

        btnDodajClana.setText("Dodaj clana grupe");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        btnObrisiClana.setText("Obrisi clana grupe");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClanovi);

        jLabel6.setText("Putnik");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(cmbPutnik, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbFakulativno, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbPutnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbFakulativno)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisiClana, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDodajClana))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnObrisiGrupu.setText("Obrisi grupu");
        btnObrisiGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiGrupuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Clanovi grupe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKAPACITET, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPrevoz, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbIzlet, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVodic, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(btnObrisiGrupu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOtkazi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(104, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbIzlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiGrupu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeni)
                        .addGap(12, 12, 12)
                        .addComponent(btnOtkazi1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPrevoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbVodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatumPolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtKAPACITET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

    try {
        if (txtKAPACITET.getText().isEmpty() || txtDatumPolaska.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }
        
        
        int kapacitetGrupe = Integer.parseInt(txtKAPACITET.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datumPolaska  = sdf.parse(txtDatumPolaska.getText());
        
        Vodic v= (Vodic) cmbVodic.getSelectedItem();
        String prevoz = (String) cmbPrevoz.getSelectedItem();
        
        TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();
        
        g.setKapacitetGrupe(kapacitetGrupe);
        g.setDatumPolaska(datumPolaska);
        g.setVodic(v);
        g.setPrevoz(prevoz);
        g.setClanovi(tm.getLista());
        
        KlijentKontroler.getInstance().izmeniGrupu(g);
        GlavnaForma gf= (GlavnaForma) getParent();
         gf.refresujTabelu();
        JOptionPane.showMessageDialog(this, "Uspesno izmenjena grupa.");
        this.dispose();
    } catch (Exception ex) {
        Logger.getLogger(DetaljiGrupeForma.class.getName()).log(Level.SEVERE, null, ex);
    }
       

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnOtkazi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkazi1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkazi1ActionPerformed

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed
         Putnik p = (Putnik) cmbPutnik.getSelectedItem();
        String napomena = txtNapomena.getText();
        Boolean fakulativno= cbFakulativno.isSelected();

        if (napomena.isEmpty()) {
            napomena = "/";
        }

        Clan  c = new Clan(g, -1, napomena,fakulativno, p);

        TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();

        if (tm.postojiClan(p)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovog putnika za ovu grupu!");
            return;
        }

        tm.dodajClana(c);
       
    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed
       int row = tblClanovi.getSelectedRow();

        if (row >= 0) {
            TableModelClanovi tm = (TableModelClanovi) tblClanovi.getModel();
            tm.obrisiClana(row);
        }
        else {
            JOptionPane.showMessageDialog(this, "Izaberite red!");
            return;
        }
    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void btnObrisiGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiGrupuActionPerformed
        int rezultat = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "obrisete ovu grupu?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (rezultat == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise grupu.");
            return;
        }

        if (rezultat == JOptionPane.YES_OPTION) {
            
            try {
                KlijentKontroler.getInstance().obrisiGrupu(g);
                GlavnaForma gf= (GlavnaForma) getParent();
                gf.refresujTabelu();
                JOptionPane.showMessageDialog(this, "Uspesno obrisana grupa.");
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(DetaljiGrupeForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
    }//GEN-LAST:event_btnObrisiGrupuActionPerformed

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnObrisiGrupu;
    private javax.swing.JButton btnOtkazi1;
    private javax.swing.JCheckBox cbFakulativno;
    private javax.swing.JComboBox<Object> cmbIzlet;
    private javax.swing.JComboBox<String> cmbPrevoz;
    private javax.swing.JComboBox<Object> cmbPutnik;
    private javax.swing.JComboBox<Object> cmbVodic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTextField txtDatumPolaska;
    private javax.swing.JTextField txtKAPACITET;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        cmbIzlet.getModel().setSelectedItem(g.getIzlet());
        cmbIzlet.setEnabled(false);
        popuniVodice();
        cmbVodic.getModel().setSelectedItem(g.getVodic());
        cmbPrevoz.getModel().setSelectedItem(g.getPrevoz());
        txtKAPACITET.setText(String.valueOf(g.getKapacitetGrupe()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumPolaska.setText(sdf.format(g.getDatumPolaska()));
        popuniPutnike();
        tblClanovi.setModel(new TableModelClanovi(g));

        if (!g.getDatumPolaska().after(new Date())) {
            cmbPutnik.setEnabled(false);
            cmbPrevoz.setEnabled(false);
            cmbVodic.setEnabled(false);
            btnDodajClana.setEnabled(false);
            btnObrisiClana.setEnabled(false);
            btnIzmeni.setEnabled(false);
            txtKAPACITET.setEditable(false);
            txtDatumPolaska.setEditable(false);
            JOptionPane.showMessageDialog(this, "Datum polaska grupe je prosao, ne mozete je menjati!");
        }

    }



    private void popuniVodice() {
        try {
            ArrayList<Vodic> vodici= KlijentKontroler.getInstance().getSveVodice();
            
            cmbVodic.removeAllItems();

            for (Vodic v: vodici) {
                cmbVodic.addItem(v);
            }
        } catch (Exception ex) {
            Logger.getLogger(NovaGrupaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniPutnike() {
     
        try {
            ArrayList<Putnik> putnici = KlijentKontroler.getInstance().getSvePutnike();

            cmbPutnik.removeAllItems();

            for (Putnik putnik : putnici) {
                cmbPutnik.addItem(putnik);
            }
        } catch (Exception ex) {
            Logger.getLogger(NovaGrupaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        
}
    
    
}
